import Head from 'next/head'
import Header from '../components/layout/Header'
import PostsContainer from '../components/layout/posts/PostsContainer'

export default function Home() {
  return (
    <div className="bg-gray-bg dark:bg-black dark:text-main-gray font-sans text-[18px]">
      <Head>
        <title>Debilana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <PostsContainer />
      </main>
    </div>
  )
}
