import Head from 'next/head'
import Header from '../components/layout/Header'

export default function Home() {
  return (
    <div className="bg-gray-bg dark:bg-black dark:text-main-gray h-screen font-sans text-[20px]">
      <Head>
        <title>Debilana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main></main>
    </div>
  )
}
